INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W001', 'Państwo: USA',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W002', 'Państwo: Wielka Brytania',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W003', 'Państwo: Francja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W004', 'Państwo: Kanada',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W005', 'Państwo: Niemcy',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W006', 'Państwo: Holandia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W007', 'Państwo: Włochy',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W008', 'Państwo: Austria',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W009', 'Państwo: Japonia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W010', 'Państwo: Turcja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W011', 'Państwo: Belgia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W012', 'Państwo: Dania',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W013', 'Państwo: Norwegia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W014', 'Państwo: Grecja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W015', 'Państwo: Australia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W016', 'Państwo: Algieria',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W017', 'Państwo: Afganistan',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W018', 'Państwo: Argentyna',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W019', 'Państwo: Brazylia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W020', 'Państwo: Bangladesz',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W021', 'Państwo: Egipt',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W022', 'Państwo: Ekwador',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W023', 'Państwo: Finlandia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W024', 'Państwo: Hiszpania',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W025', 'Państwo: Irak',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W026', 'Państwo: Iran',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W027', 'Państwo: Indie',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W028', 'Państwo: Indonezja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W029', 'Państwo: Kolumbia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W030', 'Państwo: Malezja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W031', 'Państwo: Libia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W032', 'Państwo: Maroko',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W033', 'Państwo: Meksyk',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W034', 'Państwo: Nigeria',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W035', 'Państwo: Pakistan',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W036', 'Państwo: Portugalia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W037', 'Państwo: Palestyna',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W038', 'Państwo: Syria',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W039', 'Państwo: Szwecja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W040', 'Państwo: Szwajcaria',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W041', 'Państwo: Tunezja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W042', 'Państwo: Tajlandia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W043', 'Państwo: Wenezuela',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W044', 'Państwo: Urugwaj',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W045', 'Państwo: Peru',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W046', 'Państwo: Jemen',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W047', 'Państwo: Kostaryka',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W048', 'Państwo: Kongo',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W049', 'Państwo: Izrael',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W050', 'Państwo: Nikaragua',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W051', 'Państwo: Chile',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W052', 'Państwo: Watykan',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W053', 'Państwo: Korea Południowa',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W054', 'Komisja Wspólnot Europejskich',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W055', 'Państwo: Irlandia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W056', 'Bank Światowy',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W057', 'Międzynarodowy Fundusz Walutowy',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W058', 'Państwo: Filipiny',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W059', 'Międzynarodowa Korporacja Finansowa',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W060', 'Państwo: RPA',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W061', 'Biuro ODIHR',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W062', 'Państwo: Cypr',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W063', 'Państwo: Kuwejt',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W064', 'Organizacja Narodów Zjednoczonych',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W065', 'Państwo: Rosja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W066', 'Państwo: Słowacja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W067', 'Państwo: Czechy',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W068', 'Państwo: Bułgaria',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W069', 'Państwo: Węgry',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W070', 'Państwo: Rumunia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W071', 'Państwo: Wietnam',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W072', 'Państwo: Serbia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W073', 'Państwo: Korea Północna',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W074', 'Państwo: Kuba',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W075', 'Państwo: Albania',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W076', 'Państwo: Chiny',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W077', 'Państwo: Mongolia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W078', 'Międzynarodowa Organizacja Pracy',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W079', 'Organizacja Kooperacyjna ds. Kolei',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W080', 'Klub Dyplomatyczny',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W081', 'Państwo: Laos',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W082', 'Państwo: Angola',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W083', 'Państwo: Ukraina',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W084', 'Europejski Bank Odbudowy i Rozwoju',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W085', 'Państwo: Litwa',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W086', 'Państwo: Białoruś',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W087', 'Państwo: Łotwa',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W088', 'Państwo: Chorwacja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W089', 'Państwo: Liban',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W090', 'Państwo: Słowenia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W091', 'Państwo: Gwatemala',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W092', 'Państwo: Estonia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W093', 'Państwo: Macedonia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W094', 'Państwo: Mołdawia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W095', 'Państwo: Izrael',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W096', 'Państwo: Armenia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W097', 'Państwo: Sri Lanka',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W098', 'Państwo: Kazachstan',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W099', 'Państwo: Arabia Saudyjska',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W100', 'Państwo: Gruzja',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W101', 'Państwo: Uzbekistan',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W102', 'UN-HABITAT',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W103', 'Państwo: Nowa Zelandia',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W104', 'Państwo: Azerbejdżan',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W105', 'Suwerenny Wojskowy Zakon Maltański',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W106', 'Państwo: Kambodża',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W107', 'Frontex',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W108', 'Państwo: Luksemburg',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W109', 'Państwo: Bośnia i Hercegowina',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W110', 'Państwo: Panama',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W111', 'Państwo: Katar',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W112', 'Państwo: Malta',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W113', 'Państwo: Zjednoczone Emiraty Arabskie',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W114', 'Państwo: Czarnogóra',5,'#dpc', 1);
INSERT INTO places (plate, place_name, place_type, voivodeship,  has_own_plate) VALUES ('W115', 'Państwo: Senegal' ,5,'#dpc', 1);